"""
HTMX Routes for Price Offers

Add these routes to main.py for the multi-offer procurement feature.

Generated by Gemini, evaluated by Claude
"""

# -----------------------------------------------------------------------------
# HTMX ROUTES FOR PRICE OFFERS
# Add to main.py after other procurement routes
# -----------------------------------------------------------------------------

# Example route implementations (adapt to your FastHTML patterns):

"""
# GET /quote-items/{item_id}/offers - List all offers for item
@app.get("/quote-items/{item_id}/offers")
async def get_item_offers(request, item_id: str):
    user = await get_user_from_request(request)
    if not user:
        return RedirectResponse("/login")

    offers = price_offer_service.get_offers_for_item(item_id)
    suppliers = supplier_service.get_suppliers_for_org(user.organization_id)

    return _render_offers_list(item_id, offers, suppliers)


# POST /quote-items/{item_id}/offers - Create new offer
@app.post("/quote-items/{item_id}/offers")
async def create_item_offer(request, item_id: str):
    user = await get_user_from_request(request)
    if not user:
        return Response(status_code=401)

    form = await request.form()

    offer = price_offer_service.create_offer(
        quote_item_id=item_id,
        supplier_id=form.get("supplier_id"),
        price=Decimal(form.get("price", "0")),
        currency=form.get("currency", "USD"),
        production_days=int(form.get("production_days", 0)),
        notes=form.get("notes"),
        user_id=str(user.id),
    )

    # Return updated offers list via HTMX OOB swap
    offers = price_offer_service.get_offers_for_item(item_id)
    suppliers = supplier_service.get_suppliers_for_org(user.organization_id)

    return _render_offers_list(item_id, offers, suppliers)


# POST /offers/{offer_id}/select - Select an offer
@app.post("/offers/{offer_id}/select")
async def select_offer(request, offer_id: str):
    user = await get_user_from_request(request)
    if not user:
        return Response(status_code=401)

    offer = price_offer_service.get_offer_by_id(offer_id)
    if not offer:
        return Response(status_code=404)

    # Select offer (atomic operation)
    price_offer_service.select_offer(offer_id, str(offer.quote_item_id))

    # Sync selected data to quote_item fields (for calculation compatibility)
    price_offer_service.sync_selected_to_item(str(offer.quote_item_id))

    # Return updated offers list
    offers = price_offer_service.get_offers_for_item(str(offer.quote_item_id))
    suppliers = supplier_service.get_suppliers_for_org(user.organization_id)

    return _render_offers_list(str(offer.quote_item_id), offers, suppliers)


# DELETE /offers/{offer_id} - Delete an offer
@app.delete("/offers/{offer_id}")
async def delete_offer(request, offer_id: str):
    user = await get_user_from_request(request)
    if not user:
        return Response(status_code=401)

    offer = price_offer_service.get_offer_by_id(offer_id)
    if not offer:
        return Response(status_code=404)

    quote_item_id = str(offer.quote_item_id)
    was_selected = offer.is_selected

    price_offer_service.delete_offer(offer_id)

    # If deleted offer was selected, clear quote_item fields
    if was_selected:
        supabase = get_supabase()
        supabase.table("quote_items").update({
            "supplier_id": None,
            "purchase_price_original": None,
            "purchase_currency": None,
        }).eq("id", quote_item_id).execute()

    # Return updated offers list
    offers = price_offer_service.get_offers_for_item(quote_item_id)
    suppliers = supplier_service.get_suppliers_for_org(user.organization_id)

    return _render_offers_list(quote_item_id, offers, suppliers)
"""
