"""
UI Components for Price Offers

FastHTML/HTMX components for rendering price offers UI.

Generated by Gemini, evaluated by Claude
"""

from fasthtml.common import *
from decimal import Decimal
from typing import List, Optional

# Example imports (adapt to your project structure):
# from services.price_offer_service import PriceOffer
# from services.supplier_service import Supplier


def _render_offers_list(
    item_id: str,
    offers: List,  # List[PriceOffer]
    suppliers: List,  # List[Supplier]
    expanded: bool = False
) -> Div:
    """
    Render the price offers list for a quote item.

    Args:
        item_id: Quote item UUID
        offers: List of PriceOffer objects
        suppliers: List of available suppliers for dropdown
        expanded: Whether to show expanded view by default

    Returns:
        FastHTML Div element with offers table and add form
    """
    # Format price with currency
    def format_price(offer) -> str:
        return f"{offer.currency} {offer.price:,.2f}"

    # Offers table
    offer_rows = []
    for offer in offers:
        is_selected = offer.is_selected

        offer_rows.append(
            Tr(
                # Radio button for selection
                Td(
                    Input(
                        type="radio",
                        name=f"selected_offer_{item_id}",
                        checked=is_selected,
                        hx_post=f"/offers/{offer.id}/select",
                        hx_target=f"#offers-container-{item_id}",
                        hx_swap="outerHTML",
                        cls="form-radio"
                    ),
                    cls="text-center"
                ),
                # Supplier name
                Td(
                    offer.supplier_name or "Unknown",
                    cls="font-medium" if is_selected else ""
                ),
                # Price with currency
                Td(
                    format_price(offer),
                    cls="text-right font-mono " + ("font-bold text-green-600" if is_selected else "")
                ),
                # Production days
                Td(
                    f"{offer.production_days} дн." if offer.production_days else "—",
                    cls="text-center"
                ),
                # Delete button
                Td(
                    Button(
                        "✕",
                        hx_delete=f"/offers/{offer.id}",
                        hx_target=f"#offers-container-{item_id}",
                        hx_swap="outerHTML",
                        hx_confirm="Удалить это предложение?",
                        cls="btn btn-xs btn-ghost text-red-500 hover:bg-red-100"
                    ),
                    cls="text-center"
                ),
                cls="hover:bg-gray-50" + (" bg-green-50" if is_selected else "")
            )
        )

    # Empty state
    if not offers:
        offer_rows.append(
            Tr(
                Td(
                    "Нет предложений. Добавьте первое предложение ниже.",
                    colspan=5,
                    cls="text-center text-gray-500 py-4"
                )
            )
        )

    # Table
    offers_table = Table(
        Thead(
            Tr(
                Th("", cls="w-10"),  # Radio
                Th("Поставщик", cls="text-left"),
                Th("Цена", cls="text-right"),
                Th("Срок", cls="text-center"),
                Th("", cls="w-10"),  # Delete
            ),
            cls="bg-gray-100"
        ),
        Tbody(*offer_rows),
        cls="table table-compact w-full"
    )

    # Add offer form (collapsed by default)
    add_form = Form(
        Div(
            # Supplier select
            Div(
                Label("Поставщик", cls="label-text"),
                Select(
                    Option("Выберите поставщика...", value="", disabled=True, selected=True),
                    *[Option(s.name, value=str(s.id)) for s in suppliers],
                    name="supplier_id",
                    required=True,
                    cls="select select-bordered select-sm w-full"
                ),
                cls="form-control"
            ),
            # Price and currency in row
            Div(
                Div(
                    Label("Цена", cls="label-text"),
                    Input(
                        type="number",
                        name="price",
                        step="0.01",
                        min="0",
                        required=True,
                        placeholder="0.00",
                        cls="input input-bordered input-sm w-full"
                    ),
                    cls="form-control flex-1"
                ),
                Div(
                    Label("Валюта", cls="label-text"),
                    Select(
                        Option("USD", value="USD"),
                        Option("EUR", value="EUR"),
                        Option("RUB", value="RUB"),
                        Option("CNY", value="CNY"),
                        Option("TRY", value="TRY"),
                        name="currency",
                        cls="select select-bordered select-sm"
                    ),
                    cls="form-control w-24"
                ),
                cls="flex gap-2"
            ),
            # Production days
            Div(
                Label("Срок производства (дни)", cls="label-text"),
                Input(
                    type="number",
                    name="production_days",
                    min="0",
                    placeholder="0",
                    cls="input input-bordered input-sm w-full"
                ),
                cls="form-control"
            ),
            # Notes
            Div(
                Label("Заметки", cls="label-text"),
                Textarea(
                    name="notes",
                    placeholder="Условия, комментарии...",
                    rows=2,
                    cls="textarea textarea-bordered textarea-sm w-full"
                ),
                cls="form-control"
            ),
            # Submit button
            Div(
                Button(
                    "+ Добавить предложение",
                    type="submit",
                    cls="btn btn-primary btn-sm"
                ),
                cls="mt-2"
            ),
            cls="space-y-2 p-3 bg-gray-50 rounded-lg mt-2"
        ),
        hx_post=f"/quote-items/{item_id}/offers",
        hx_target=f"#offers-container-{item_id}",
        hx_swap="outerHTML",
    )

    # Toggle for add form
    toggle_btn = Button(
        "+ Новое предложение",
        cls="btn btn-ghost btn-xs text-primary",
        onclick="this.nextElementSibling.classList.toggle('hidden')"
    )

    # Wrap add form in collapsible div
    add_form_wrapper = Div(
        add_form,
        cls="hidden" if not expanded else ""
    )

    # Container with count badge
    offer_count = len(offers)
    selected = next((o for o in offers if o.is_selected), None)

    header = Div(
        Span(f"Предложения ({offer_count})", cls="font-medium"),
        Span(
            f"✓ Выбрано: {selected.supplier_name}" if selected else "⚠ Не выбрано",
            cls="text-sm " + ("text-green-600" if selected else "text-orange-500")
        ),
        cls="flex justify-between items-center mb-2"
    )

    return Div(
        header,
        offers_table,
        toggle_btn,
        add_form_wrapper,
        id=f"offers-container-{item_id}",
        cls="border rounded-lg p-3 bg-white"
    )


def _render_offers_badge(offers_count: int, has_selected: bool) -> Span:
    """
    Render a small badge showing offer status.
    Use this in the items table to indicate offer status.

    Args:
        offers_count: Number of offers for item
        has_selected: Whether an offer is selected

    Returns:
        FastHTML Span with badge
    """
    if offers_count == 0:
        return Span(
            "—",
            cls="text-gray-400"
        )

    if has_selected:
        return Span(
            f"✓ {offers_count}",
            cls="badge badge-sm badge-success"
        )

    return Span(
        f"⚠ {offers_count}",
        cls="badge badge-sm badge-warning",
        title="Предложение не выбрано"
    )
