export type {
  Customer,
  CustomerContact,
  CustomerCall,
  CustomerContract,
  CustomerListItem,
  CustomerFinancials,
  CustomerStats,
  PhoneEntry,
  ContractFormData,
} from "./types";
export {
  fetchCustomersList,
  fetchCustomerFinancials,
  fetchCustomerDetail,
  canAccessCustomer,
  fetchCustomerStats,
  fetchCustomerContacts,
  fetchCustomerAddresses,
  fetchCustomerContracts,
  fetchCustomerCalls,
  fetchCustomerQuotes,
  fetchCustomerSpecs,
  fetchCustomerPositions,
  fetchOrgUsers,
} from "./queries";
export type {
  ContactFormData,
  CallFormData,
  AddressFormData,
  CreateCustomerData,
} from "./mutations";
export {
  createCustomer,
  createContact,
  updateContact,
  deleteContact,
  createCall,
  updateCustomerNotes,
  updateCustomerAddresses,
  updateCustomerGeneralEmail,
  createDeliveryAddress,
  createContract,
  updateContract,
  deleteContract,
} from "./mutations";
