"""
Tests for XLS Export Service

Tests invoice XLS generation with mock Supabase data.
Verifies: valid XLSX output, RU/EN headers, EN name fallback, empty items.
"""

from io import BytesIO
from unittest.mock import patch, MagicMock

import pytest
from openpyxl import load_workbook


# --- Test data fixtures ---

MOCK_INVOICE = {
    "id": "inv-001",
    "quote_id": "q-001",
    "supplier_id": "sup-001",
    "invoice_number": "INV-2026-001",
    "currency": "USD",
    "supplier_incoterms": "FOB",
    "suppliers": {
        "id": "sup-001",
        "name": "Acme Bearings Ltd",
    },
}

MOCK_ITEMS = [
    {
        "id": "item-001",
        "brand": "SKF",
        "idn_sku": "SKF-6205",
        "supplier_sku": "6205-2RS1",
        "manufacturer_product_name": "SKF Group",
        "product_name": "Подшипник шариковый",
        "name_en": "Ball Bearing",
        "quantity": 100,
        "min_order_quantity": 50,
        "purchase_price_original": 12.50,
        "production_time_days": 30,
        "weight_kg": 0.15,
        "dimension_height_mm": 52,
        "dimension_width_mm": 52,
        "dimension_length_mm": 15,
        "procurement_notes": "Срочная поставка",
    },
    {
        "id": "item-002",
        "brand": "FAG",
        "idn_sku": "FAG-22220",
        "supplier_sku": None,
        "manufacturer_product_name": None,
        "product_name": "Подшипник роликовый",
        "name_en": None,
        "quantity": 20,
        "min_order_quantity": None,
        "purchase_price_original": 85.00,
        "production_time_days": 45,
        "weight_kg": 3.2,
        "dimension_height_mm": None,
        "dimension_width_mm": None,
        "dimension_length_mm": None,
        "procurement_notes": None,
    },
]


def _build_mock_supabase(invoice_data=None, items_data=None):
    """Build a mock supabase client that returns given data for chained queries."""
    mock_sb = MagicMock()

    def table_side_effect(table_name):
        mock_table = MagicMock()
        mock_select = MagicMock()
        mock_eq = MagicMock()
        mock_order = MagicMock()

        if table_name == "invoices":
            execute_result = MagicMock()
            execute_result.data = [invoice_data] if invoice_data else []
            mock_eq.execute.return_value = execute_result
            mock_select.eq.return_value = mock_eq
            mock_table.select.return_value = mock_select
        elif table_name == "quote_items":
            execute_result = MagicMock()
            execute_result.data = items_data if items_data is not None else []
            mock_order.execute.return_value = execute_result
            mock_eq.order.return_value = mock_order
            mock_select.eq.return_value = mock_eq
            mock_table.select.return_value = mock_select

        return mock_table

    mock_sb.table.side_effect = table_side_effect
    return mock_sb


# --- Column header constants (must match service) ---

RU_HEADERS = [
    "Бренд",
    "Арт. запрошенный",
    "Арт. производителя",
    "Наименование производителя",
    "Наименование",
    "Кол-во",
    "Мин. заказ",
    "Цена",
    "Срок (к.д.)",
    "Вес (кг)",
    "Размеры (В×Ш×Д мм)",
    "Примечание",
]

EN_HEADERS = [
    "Brand",
    "Requested SKU",
    "Manufacturer SKU",
    "Manufacturer Name",
    "Item Name",
    "Quantity",
    "MOQ",
    "Price",
    "Lead Time (days)",
    "Weight (kg)",
    "Dimensions (HxWxL mm)",
    "Notes",
]


class TestGenerateInvoiceXls:
    """Tests for generate_invoice_xls."""

    @patch("services.xls_export_service.get_supabase")
    def test_returns_valid_xlsx_bytes(self, mock_get_sb):
        """Generated bytes are a valid XLSX file loadable by openpyxl."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")

        assert isinstance(result, bytes)
        assert len(result) > 0

        # Verify it's a valid XLSX by loading it
        wb = load_workbook(BytesIO(result))
        assert len(wb.sheetnames) >= 1
        ws = wb.active
        # Header row + 2 item rows = 3 rows minimum
        assert ws.max_row >= 3

    @patch("services.xls_export_service.get_supabase")
    def test_ru_language_has_russian_headers(self, mock_get_sb):
        """RU language produces Russian column headers."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        actual_headers = [ws.cell(row=1, column=i + 1).value for i in range(len(RU_HEADERS))]
        assert actual_headers == RU_HEADERS

    @patch("services.xls_export_service.get_supabase")
    def test_en_language_has_english_headers(self, mock_get_sb):
        """EN language produces English column headers."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="en")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        actual_headers = [ws.cell(row=1, column=i + 1).value for i in range(len(EN_HEADERS))]
        assert actual_headers == EN_HEADERS

    @patch("services.xls_export_service.get_supabase")
    def test_en_fallback_uses_russian_name_when_name_en_is_null(self, mock_get_sb):
        """When language='en' and name_en is NULL, falls back to Russian product_name."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="en")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        # Item 1 has name_en="Ball Bearing" -> should use it
        name_col_index = EN_HEADERS.index("Item Name") + 1
        assert ws.cell(row=2, column=name_col_index).value == "Ball Bearing"

        # Item 2 has name_en=None -> should fall back to Russian name
        assert ws.cell(row=3, column=name_col_index).value == "Подшипник роликовый"

    @patch("services.xls_export_service.get_supabase")
    def test_en_mixed_items_some_with_name_en_some_without(self, mock_get_sb):
        """EN XLS handles mixed items: some with name_en, some without — both present."""
        mixed_items = [
            {
                "id": "item-a",
                "brand": "SKF",
                "idn_sku": "SKF-A",
                "supplier_sku": "A-1",
                "manufacturer_product_name": "SKF",
                "product_name": "Подшипник A",
                "name_en": "Bearing A",
                "quantity": 10,
                "min_order_quantity": 5,
                "purchase_price_original": 1.0,
                "production_time_days": 10,
                "weight_kg": 0.1,
                "dimension_height_mm": None,
                "dimension_width_mm": None,
                "dimension_length_mm": None,
                "procurement_notes": None,
            },
            {
                "id": "item-b",
                "brand": "FAG",
                "idn_sku": "FAG-B",
                "supplier_sku": "B-1",
                "manufacturer_product_name": "FAG",
                "product_name": "Подшипник B",
                "name_en": None,
                "quantity": 20,
                "min_order_quantity": None,
                "purchase_price_original": 2.0,
                "production_time_days": 20,
                "weight_kg": 0.2,
                "dimension_height_mm": None,
                "dimension_width_mm": None,
                "dimension_length_mm": None,
                "procurement_notes": None,
            },
            {
                "id": "item-c",
                "brand": "NSK",
                "idn_sku": "NSK-C",
                "supplier_sku": "C-1",
                "manufacturer_product_name": "NSK",
                "product_name": "Подшипник C",
                "name_en": "Bearing C",
                "quantity": 30,
                "min_order_quantity": None,
                "purchase_price_original": 3.0,
                "production_time_days": 30,
                "weight_kg": 0.3,
                "dimension_height_mm": None,
                "dimension_width_mm": None,
                "dimension_length_mm": None,
                "procurement_notes": None,
            },
        ]
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, mixed_items)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="en")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        name_col = EN_HEADERS.index("Item Name") + 1
        # Row 2: name_en present -> English
        assert ws.cell(row=2, column=name_col).value == "Bearing A"
        # Row 3: name_en NULL -> Russian fallback
        assert ws.cell(row=3, column=name_col).value == "Подшипник B"
        # Row 4: name_en present -> English
        assert ws.cell(row=4, column=name_col).value == "Bearing C"

        # All three items are in the sheet
        assert ws.max_row == 4  # 1 header + 3 items

    @patch("services.xls_export_service.get_supabase")
    def test_ru_always_uses_russian_name(self, mock_get_sb):
        """When language='ru', always uses product_name regardless of name_en."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        name_col_index = RU_HEADERS.index("Наименование") + 1
        assert ws.cell(row=2, column=name_col_index).value == "Подшипник шариковый"
        assert ws.cell(row=3, column=name_col_index).value == "Подшипник роликовый"

    @patch("services.xls_export_service.get_supabase")
    def test_empty_items_returns_valid_xls_with_headers_only(self, mock_get_sb):
        """Empty items list produces valid XLS with header row only."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, [])

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")

        assert isinstance(result, bytes)
        assert len(result) > 0

        wb = load_workbook(BytesIO(result))
        ws = wb.active

        # Should have header row only
        assert ws.max_row == 1

        # Headers still present
        actual_headers = [ws.cell(row=1, column=i + 1).value for i in range(len(RU_HEADERS))]
        assert actual_headers == RU_HEADERS

    @patch("services.xls_export_service.get_supabase")
    def test_item_data_mapped_correctly(self, mock_get_sb):
        """Verify all item fields are mapped to correct columns."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        # Check first item row (row 2)
        assert ws.cell(row=2, column=1).value == "SKF"                  # brand
        assert ws.cell(row=2, column=2).value == "SKF-6205"             # idn_sku
        assert ws.cell(row=2, column=3).value == "6205-2RS1"            # supplier_sku
        assert ws.cell(row=2, column=4).value == "SKF Group"            # manufacturer_product_name
        assert ws.cell(row=2, column=5).value == "Подшипник шариковый"  # product_name (RU)
        assert ws.cell(row=2, column=6).value == 100                    # quantity
        assert ws.cell(row=2, column=7).value == 50                     # min_order_quantity
        assert ws.cell(row=2, column=8).value == 12.50                  # purchase_price_original
        assert ws.cell(row=2, column=9).value == 30                     # production_time_days
        assert ws.cell(row=2, column=10).value == 0.15                  # weight_kg
        assert ws.cell(row=2, column=11).value == "52×52×15"            # dimensions
        assert ws.cell(row=2, column=12).value == "Срочная поставка"    # procurement_notes

    @patch("services.xls_export_service.get_supabase")
    def test_dimensions_handles_null_values(self, mock_get_sb):
        """When dimension fields are NULL, dimensions column is empty."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        # Item 2 has all dimensions as None
        assert ws.cell(row=3, column=11).value is None

    @patch("services.xls_export_service.get_supabase")
    def test_header_row_is_bold_with_gray_background(self, mock_get_sb):
        """Header row should be styled: bold font, light gray fill."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        for col_idx in range(1, len(RU_HEADERS) + 1):
            cell = ws.cell(row=1, column=col_idx)
            assert cell.font.bold is True, f"Column {col_idx} header should be bold"
            assert cell.fill.start_color.rgb is not None, f"Column {col_idx} should have fill"
            assert cell.fill.fill_type == "solid", f"Column {col_idx} should have solid fill"
