"""
Tests for XLS Export Service

Tests invoice XLS generation with mock Supabase data.
Verifies: valid XLSX output, RU/EN headers, EN name fallback, empty items.

Phase 5d (Task 3): reads from kvota.invoice_items (not quote_items) + the
invoice_item_coverage JOIN. Split invoice_items appear as independent rows;
merged invoice_items get a "Покрывает" column listing the source quote_items.
"""

from io import BytesIO
from unittest.mock import patch, MagicMock

import pytest
from openpyxl import load_workbook


# --- Test data fixtures ---

MOCK_INVOICE = {
    "id": "inv-001",
    "quote_id": "q-001",
    "supplier_id": "sup-001",
    "invoice_number": "INV-2026-001",
    "currency": "USD",
    "supplier_incoterms": "FOB",
    "suppliers": {
        "id": "sup-001",
        "name": "Acme Bearings Ltd",
    },
}

# Each row represents an invoice_items row with its embedded coverage list.
# The PostgREST embedded query populates invoice_item_coverage[].quote_items
# with the requested columns (product_name, quantity, idn_sku,
# manufacturer_product_name, name_en) from each linked quote_item.
MOCK_ITEMS = [
    {
        "id": "item-001",
        "brand": "SKF",
        "supplier_sku": "6205-2RS1",
        "product_name": "Подшипник шариковый",
        "quantity": 100,
        "minimum_order_quantity": 50,
        "purchase_price_original": 12.50,
        "production_time_days": 30,
        "weight_in_kg": 0.15,
        "dimension_height_mm": 52,
        "dimension_width_mm": 52,
        "dimension_length_mm": 15,
        "supplier_notes": "Срочная поставка",
        "invoice_item_coverage": [
            {
                "quote_item_id": "qi-001",
                "ratio": 1,
                "quote_items": {
                    "product_name": "Подшипник шариковый",
                    "quantity": 100,
                    "idn_sku": "SKF-6205",
                    "manufacturer_product_name": "SKF Group",
                    "name_en": "Ball Bearing",
                },
            }
        ],
    },
    {
        "id": "item-002",
        "brand": "FAG",
        "supplier_sku": None,
        "product_name": "Подшипник роликовый",
        "quantity": 20,
        "minimum_order_quantity": None,
        "purchase_price_original": 85.00,
        "production_time_days": 45,
        "weight_in_kg": 3.2,
        "dimension_height_mm": None,
        "dimension_width_mm": None,
        "dimension_length_mm": None,
        "supplier_notes": None,
        "invoice_item_coverage": [
            {
                "quote_item_id": "qi-002",
                "ratio": 1,
                "quote_items": {
                    "product_name": "Подшипник роликовый",
                    "quantity": 20,
                    "idn_sku": "FAG-22220",
                    "manufacturer_product_name": None,
                    "name_en": None,
                },
            }
        ],
    },
]


def _build_mock_supabase(invoice_data=None, items_data=None):
    """Build a mock supabase client that returns given data for chained queries."""
    mock_sb = MagicMock()

    def table_side_effect(table_name):
        mock_table = MagicMock()
        mock_select = MagicMock()
        mock_eq = MagicMock()
        mock_order = MagicMock()

        if table_name == "invoices":
            execute_result = MagicMock()
            execute_result.data = [invoice_data] if invoice_data else []
            mock_eq.execute.return_value = execute_result
            mock_select.eq.return_value = mock_eq
            mock_table.select.return_value = mock_select
        elif table_name == "invoice_items":
            execute_result = MagicMock()
            execute_result.data = items_data if items_data is not None else []
            mock_order.execute.return_value = execute_result
            mock_eq.order.return_value = mock_order
            mock_select.eq.return_value = mock_eq
            mock_table.select.return_value = mock_select

        return mock_table

    mock_sb.table.side_effect = table_side_effect
    return mock_sb


# --- Column header constants (must match service) ---

RU_HEADERS = [
    "Бренд",
    "Арт. запрошенный",
    "Арт. производителя",
    "Наименование производителя",
    "Наименование",
    "Кол-во",
    "Мин. заказ",
    "Цена",
    "Срок (к.д.)",
    "Вес (кг)",
    "Размеры (В×Ш×Д мм)",
    "Примечание",
    "Покрывает",
]

EN_HEADERS = [
    "Brand",
    "Requested SKU",
    "Manufacturer SKU",
    "Manufacturer Name",
    "Item Name",
    "Quantity",
    "MOQ",
    "Price",
    "Lead Time (days)",
    "Weight (kg)",
    "Dimensions (HxWxL mm)",
    "Notes",
    "Covers",
]


class TestGenerateInvoiceXls:
    """Tests for generate_invoice_xls."""

    @patch("services.xls_export_service.get_supabase")
    def test_returns_valid_xlsx_bytes(self, mock_get_sb):
        """Generated bytes are a valid XLSX file loadable by openpyxl."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")

        assert isinstance(result, bytes)
        assert len(result) > 0

        # Verify it's a valid XLSX by loading it
        wb = load_workbook(BytesIO(result))
        assert len(wb.sheetnames) >= 1
        ws = wb.active
        # Header row + 2 item rows = 3 rows minimum
        assert ws.max_row >= 3

    @patch("services.xls_export_service.get_supabase")
    def test_ru_language_has_russian_headers(self, mock_get_sb):
        """RU language produces Russian column headers."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        actual_headers = [ws.cell(row=1, column=i + 1).value for i in range(len(RU_HEADERS))]
        assert actual_headers == RU_HEADERS

    @patch("services.xls_export_service.get_supabase")
    def test_en_language_has_english_headers(self, mock_get_sb):
        """EN language produces English column headers."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="en")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        actual_headers = [ws.cell(row=1, column=i + 1).value for i in range(len(EN_HEADERS))]
        assert actual_headers == EN_HEADERS

    @patch("services.xls_export_service.get_supabase")
    def test_en_fallback_uses_russian_name_when_name_en_is_null(self, mock_get_sb):
        """When language='en' and name_en is NULL, falls back to Russian product_name."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="en")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        # Item 1 has name_en="Ball Bearing" -> should use it
        name_col_index = EN_HEADERS.index("Item Name") + 1
        assert ws.cell(row=2, column=name_col_index).value == "Ball Bearing"

        # Item 2 has name_en=None -> should fall back to Russian name
        assert ws.cell(row=3, column=name_col_index).value == "Подшипник роликовый"

    @patch("services.xls_export_service.get_supabase")
    def test_en_mixed_items_some_with_name_en_some_without(self, mock_get_sb):
        """EN XLS handles mixed items: some with name_en, some without — both present."""
        mixed_items = [
            {
                "id": "item-a",
                "brand": "SKF",
                "supplier_sku": "A-1",
                "product_name": "Подшипник A",
                "quantity": 10,
                "minimum_order_quantity": 5,
                "purchase_price_original": 1.0,
                "production_time_days": 10,
                "weight_in_kg": 0.1,
                "dimension_height_mm": None,
                "dimension_width_mm": None,
                "dimension_length_mm": None,
                "supplier_notes": None,
                "invoice_item_coverage": [
                    {
                        "quote_item_id": "qi-a",
                        "ratio": 1,
                        "quote_items": {
                            "product_name": "Подшипник A",
                            "quantity": 10,
                            "idn_sku": "SKF-A",
                            "manufacturer_product_name": "SKF",
                            "name_en": "Bearing A",
                        },
                    }
                ],
            },
            {
                "id": "item-b",
                "brand": "FAG",
                "supplier_sku": "B-1",
                "product_name": "Подшипник B",
                "quantity": 20,
                "minimum_order_quantity": None,
                "purchase_price_original": 2.0,
                "production_time_days": 20,
                "weight_in_kg": 0.2,
                "dimension_height_mm": None,
                "dimension_width_mm": None,
                "dimension_length_mm": None,
                "supplier_notes": None,
                "invoice_item_coverage": [
                    {
                        "quote_item_id": "qi-b",
                        "ratio": 1,
                        "quote_items": {
                            "product_name": "Подшипник B",
                            "quantity": 20,
                            "idn_sku": "FAG-B",
                            "manufacturer_product_name": "FAG",
                            "name_en": None,
                        },
                    }
                ],
            },
            {
                "id": "item-c",
                "brand": "NSK",
                "supplier_sku": "C-1",
                "product_name": "Подшипник C",
                "quantity": 30,
                "minimum_order_quantity": None,
                "purchase_price_original": 3.0,
                "production_time_days": 30,
                "weight_in_kg": 0.3,
                "dimension_height_mm": None,
                "dimension_width_mm": None,
                "dimension_length_mm": None,
                "supplier_notes": None,
                "invoice_item_coverage": [
                    {
                        "quote_item_id": "qi-c",
                        "ratio": 1,
                        "quote_items": {
                            "product_name": "Подшипник C",
                            "quantity": 30,
                            "idn_sku": "NSK-C",
                            "manufacturer_product_name": "NSK",
                            "name_en": "Bearing C",
                        },
                    }
                ],
            },
        ]
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, mixed_items)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="en")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        name_col = EN_HEADERS.index("Item Name") + 1
        # Row 2: name_en present -> English
        assert ws.cell(row=2, column=name_col).value == "Bearing A"
        # Row 3: name_en NULL -> Russian fallback
        assert ws.cell(row=3, column=name_col).value == "Подшипник B"
        # Row 4: name_en present -> English
        assert ws.cell(row=4, column=name_col).value == "Bearing C"

        # All three items are in the sheet
        assert ws.max_row == 4  # 1 header + 3 items

    @patch("services.xls_export_service.get_supabase")
    def test_ru_always_uses_russian_name(self, mock_get_sb):
        """When language='ru', always uses product_name regardless of name_en."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        name_col_index = RU_HEADERS.index("Наименование") + 1
        assert ws.cell(row=2, column=name_col_index).value == "Подшипник шариковый"
        assert ws.cell(row=3, column=name_col_index).value == "Подшипник роликовый"

    @patch("services.xls_export_service.get_supabase")
    def test_empty_items_returns_valid_xls_with_headers_only(self, mock_get_sb):
        """Empty items list produces valid XLS with header row only."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, [])

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")

        assert isinstance(result, bytes)
        assert len(result) > 0

        wb = load_workbook(BytesIO(result))
        ws = wb.active

        # Should have header row only
        assert ws.max_row == 1

        # Headers still present
        actual_headers = [ws.cell(row=1, column=i + 1).value for i in range(len(RU_HEADERS))]
        assert actual_headers == RU_HEADERS

    @patch("services.xls_export_service.get_supabase")
    def test_item_data_mapped_correctly(self, mock_get_sb):
        """Verify all item fields are mapped to correct columns."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        # Check first item row (row 2)
        assert ws.cell(row=2, column=1).value == "SKF"                  # brand
        assert ws.cell(row=2, column=2).value == "SKF-6205"             # idn_sku
        assert ws.cell(row=2, column=3).value == "6205-2RS1"            # supplier_sku
        assert ws.cell(row=2, column=4).value == "SKF Group"            # manufacturer_product_name
        assert ws.cell(row=2, column=5).value == "Подшипник шариковый"  # product_name (RU)
        assert ws.cell(row=2, column=6).value == 100                    # quantity
        assert ws.cell(row=2, column=7).value == 50                     # min_order_quantity
        assert ws.cell(row=2, column=8).value == 12.50                  # purchase_price_original
        assert ws.cell(row=2, column=9).value == 30                     # production_time_days
        assert ws.cell(row=2, column=10).value == 0.15                  # weight_kg
        assert ws.cell(row=2, column=11).value == "52×52×15"            # dimensions
        assert ws.cell(row=2, column=12).value == "Срочная поставка"    # procurement_notes

    @patch("services.xls_export_service.get_supabase")
    def test_dimensions_handles_null_values(self, mock_get_sb):
        """When dimension fields are NULL, dimensions column is empty."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        # Item 2 has all dimensions as None
        assert ws.cell(row=3, column=11).value is None

    @patch("services.xls_export_service.get_supabase")
    def test_header_row_is_bold_with_gray_background(self, mock_get_sb):
        """Header row should be styled: bold font, light gray fill."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        for col_idx in range(1, len(RU_HEADERS) + 1):
            cell = ws.cell(row=1, column=col_idx)
            assert cell.font.bold is True, f"Column {col_idx} header should be bold"
            assert cell.fill.start_color.rgb is not None, f"Column {col_idx} should have fill"
            assert cell.fill.fill_type == "solid", f"Column {col_idx} should have solid fill"


# --- Phase 5d: invoice_items + coverage "Покрывает" column ---


class TestXlsExportPhase5d:
    """Phase 5d Task 3: XLS reads from invoice_items (not quote_items) +
    uses invoice_item_coverage for the new "Покрывает" column."""

    @patch("services.xls_export_service.get_supabase")
    def test_rows_come_from_invoice_items_not_quote_items(self, mock_get_sb):
        """Service queries kvota.invoice_items table, not kvota.quote_items."""
        mock_sb = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)
        mock_get_sb.return_value = mock_sb

        from services.xls_export_service import generate_invoice_xls

        generate_invoice_xls("inv-001", language="ru")

        # Verify the service called .table("invoice_items")
        called_tables = [call.args[0] for call in mock_sb.table.call_args_list]
        assert "invoice_items" in called_tables, (
            f"Service must read from 'invoice_items' table (got: {called_tables})"
        )
        assert "quote_items" not in called_tables, (
            f"Service must NOT read from 'quote_items' table (got: {called_tables})"
        )

    @patch("services.xls_export_service.get_supabase")
    def test_split_invoice_items_render_as_independent_rows(self, mock_get_sb):
        """1 quote_item covered by 2 invoice_items (split) -> XLS has 2 rows,
        each with its own weight/price/quantity."""
        # Split: one qi "qi-split-src" is covered by two independent invoice_items
        # with different weights and prices.
        split_items = [
            {
                "id": "ii-split-a",
                "brand": "SKF",
                "supplier_sku": "A-SKU",
                "product_name": "Split Part A",
                "quantity": 100,
                "minimum_order_quantity": None,
                "purchase_price_original": 5.00,
                "production_time_days": 10,
                "weight_in_kg": 0.5,
                "dimension_height_mm": None,
                "dimension_width_mm": None,
                "dimension_length_mm": None,
                "supplier_notes": None,
                "invoice_item_coverage": [
                    {
                        "quote_item_id": "qi-split-src",
                        "ratio": 1,
                        "quote_items": {
                            "product_name": "Original Product",
                            "quantity": 100,
                            "idn_sku": "IDN-SPLIT",
                            "manufacturer_product_name": "Orig Mfr",
                            "name_en": None,
                        },
                    }
                ],
            },
            {
                "id": "ii-split-b",
                "brand": "FAG",
                "supplier_sku": "B-SKU",
                "product_name": "Split Part B",
                "quantity": 200,
                "minimum_order_quantity": None,
                "purchase_price_original": 7.50,
                "production_time_days": 14,
                "weight_in_kg": 1.2,
                "dimension_height_mm": None,
                "dimension_width_mm": None,
                "dimension_length_mm": None,
                "supplier_notes": None,
                "invoice_item_coverage": [
                    {
                        "quote_item_id": "qi-split-src",
                        "ratio": 2,
                        "quote_items": {
                            "product_name": "Original Product",
                            "quantity": 100,
                            "idn_sku": "IDN-SPLIT",
                            "manufacturer_product_name": "Orig Mfr",
                            "name_en": None,
                        },
                    }
                ],
            },
        ]
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, split_items)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        # Header + 2 split rows
        assert ws.max_row == 3

        name_col = RU_HEADERS.index("Наименование") + 1
        weight_col = RU_HEADERS.index("Вес (кг)") + 1
        price_col = RU_HEADERS.index("Цена") + 1

        # Row 2: first split -> Part A
        assert ws.cell(row=2, column=name_col).value == "Split Part A"
        assert ws.cell(row=2, column=weight_col).value == 0.5
        assert ws.cell(row=2, column=price_col).value == 5.00

        # Row 3: second split -> Part B (independent weights/prices)
        assert ws.cell(row=3, column=name_col).value == "Split Part B"
        assert ws.cell(row=3, column=weight_col).value == 1.2
        assert ws.cell(row=3, column=price_col).value == 7.50

    @patch("services.xls_export_service.get_supabase")
    def test_merged_invoice_items_list_coverage_in_pokryvaet_column(self, mock_get_sb):
        """1 invoice_item covers 2 quote_items (merge) -> XLS has 1 row
        with 'Покрывает' column filled with comma-joined product_names."""
        merged_items = [
            {
                "id": "ii-merged",
                "brand": "NSK",
                "supplier_sku": "MERGE-SKU",
                "product_name": "Combined Part",
                "quantity": 50,
                "minimum_order_quantity": None,
                "purchase_price_original": 30.00,
                "production_time_days": 20,
                "weight_in_kg": 2.0,
                "dimension_height_mm": None,
                "dimension_width_mm": None,
                "dimension_length_mm": None,
                "supplier_notes": None,
                "invoice_item_coverage": [
                    {
                        "quote_item_id": "qi-a",
                        "ratio": 1,
                        "quote_items": {
                            "product_name": "Подшипник A",
                            "quantity": 25,
                            "idn_sku": "IDN-A",
                            "manufacturer_product_name": "NSK",
                            "name_en": None,
                        },
                    },
                    {
                        "quote_item_id": "qi-b",
                        "ratio": 1,
                        "quote_items": {
                            "product_name": "Подшипник B",
                            "quantity": 25,
                            "idn_sku": "IDN-B",
                            "manufacturer_product_name": "NSK",
                            "name_en": None,
                        },
                    },
                ],
            }
        ]
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, merged_items)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        # Header + 1 merged row (not 2)
        assert ws.max_row == 2

        pokryvaet_col = RU_HEADERS.index("Покрывает") + 1
        covers_value = ws.cell(row=2, column=pokryvaet_col).value

        # Must list both source quote_items' product names, joined by ", "
        assert covers_value is not None, "Покрывает column must be populated for merged rows"
        assert "Подшипник A" in covers_value
        assert "Подшипник B" in covers_value
        # Order-preserving join
        assert covers_value == "Подшипник A, Подшипник B"

    @patch("services.xls_export_service.get_supabase")
    def test_one_to_one_rows_have_empty_pokryvaet(self, mock_get_sb):
        """Standard 1:1 case (single coverage row) -> 'Покрывает' is NULL/empty."""
        mock_get_sb.return_value = _build_mock_supabase(MOCK_INVOICE, MOCK_ITEMS)

        from services.xls_export_service import generate_invoice_xls

        result = generate_invoice_xls("inv-001", language="ru")
        wb = load_workbook(BytesIO(result))
        ws = wb.active

        pokryvaet_col = RU_HEADERS.index("Покрывает") + 1

        # Both MOCK_ITEMS are 1:1 (single coverage entry each)
        # "Покрывает" should be empty/None for both rows
        assert ws.cell(row=2, column=pokryvaet_col).value in (None, "")
        assert ws.cell(row=3, column=pokryvaet_col).value in (None, "")
