"""
OneStack Services

Export and versioning services for quote management.
Role management services for workflow system.
Workflow service for quote status management.
Telegram bot service for notifications and approvals.
"""

from .database import get_supabase, get_anon_client
from .export_data_mapper import fetch_export_data, ExportData
from .specification_export import (
    generate_specification_pdf,
    # Feature #70: Enhanced PDF generation from specifications table
    SpecificationData,
    fetch_specification_data,
    generate_spec_pdf_html,
    generate_spec_pdf_from_spec_id,
)
from .invoice_export import generate_invoice_pdf
from .validation_export import create_validation_excel
from .quote_version_service import create_quote_version, list_quote_versions, get_quote_version
from .role_service import (
    Role,
    UserRole,
    get_user_roles,
    get_user_role_codes,
    has_role,
    has_any_role,
    has_all_roles,
    assign_role,
    remove_role,
    get_all_roles,
    get_role_by_code,
    get_users_by_role,
    get_users_by_any_role,
    # Route protection middleware
    require_role,
    require_any_role,
    require_all_roles,
    get_session_user_roles,
)
from .brand_service import (
    # Data class
    BrandAssignment,
    # Create operations
    create_brand_assignment,
    upsert_brand_assignment,
    bulk_create_assignments,
    # Read operations
    get_brand_assignment,
    get_brand_assignment_by_brand,
    get_all_brand_assignments,
    get_user_brand_assignments,
    get_assignments_with_user_details,
    # Update operations
    update_brand_assignment,
    reassign_brand,
    # Delete operations
    delete_brand_assignment,
    delete_brand_assignment_by_brand,
    delete_all_user_assignments,
    # Convenience functions (Features #31, #32)
    get_procurement_manager,
    get_assigned_brands,
    # Utility functions
    get_unique_brands_in_org,
    get_unassigned_brands,
    get_brand_manager_mapping,
    count_assignments_by_user,
    is_brand_assigned,
)
from .workflow_service import (
    # Enum and data classes
    WorkflowStatus,
    StatusTransition,
    TransitionResult,
    # Status metadata
    STATUS_NAMES,
    STATUS_NAMES_SHORT,
    STATUS_COLORS,
    IN_PROGRESS_STATUSES,
    FINAL_STATUSES,
    ALLOWED_TRANSITIONS,
    # Helper functions
    get_status_name,
    get_status_name_short,
    get_status_color,
    get_allowed_transitions,
    get_allowed_target_statuses,
    can_transition,
    is_final_status,
    is_in_progress,
    get_workflow_order,
    get_workflow_stage,
    get_all_statuses,
    # Permission matrix functions (Feature #24)
    get_transition_requirements,
    get_roles_for_transition,
    get_transitions_by_role,
    get_permission_matrix,
    get_permission_matrix_detailed,
    get_outgoing_transitions,
    get_incoming_transitions,
    is_comment_required,
    is_auto_transition,
    # Transition execution functions (Feature #25)
    transition_quote_status,
    get_quote_workflow_status,
    get_quote_transition_history,
    get_available_transitions_for_quote,
    # Auto-transition functions (Feature #28)
    check_and_auto_transition_to_sales_review,
    complete_logistics,
    complete_customs,
    get_parallel_stages_status,
    # Procurement assignment functions (Feature #29)
    get_procurement_users_for_quote,
    assign_procurement_users_to_quote,
    transition_to_pending_procurement,
    get_quote_procurement_status,
)
from .approval_service import (
    # Data classes
    Approval,
    ApprovalRequestResult,
    ApprovalDecisionResult,
    ModificationValidationResult,
    ApprovalWithModificationsResult,
    ApplyModificationsResult,
    # Create operations
    create_approval,
    create_approvals_for_role,
    # Read operations
    get_approval,
    get_approval_by_quote,
    get_approvals_for_quote,
    get_pending_approval_for_quote,
    get_pending_approvals_for_user,
    get_approvals_requested_by,
    get_approvals_with_details,
    count_pending_approvals,
    # Update operations
    update_approval_status,
    approve_quote_approval,
    reject_quote_approval,
    # Delete operations
    cancel_pending_approvals_for_quote,
    # Utility functions
    has_pending_approval,
    get_latest_approval_decision,
    get_approval_stats_for_user,
    # High-level workflow functions (Feature #65, #66)
    request_approval,
    process_approval_decision,
    # WF-005: Approval with modifications (v3.0)
    ALLOWED_QUOTE_MODIFICATIONS,
    ALLOWED_ITEM_MODIFICATIONS,
    validate_modifications,
    approve_with_modifications,
    apply_modifications_to_quote,
    get_approval_modifications,
    get_modifications_summary,
    get_approvals_with_modifications,
)
from .specification_service import (
    # Data class
    Specification,
    CreateSpecFromQuoteResult,
    # Constants
    SPEC_STATUSES,
    SPEC_STATUS_NAMES,
    SPEC_STATUS_COLORS,
    SPEC_TRANSITIONS,
    # Status helpers
    get_spec_status_name,
    get_spec_status_color,
    can_transition_spec,
    get_allowed_spec_transitions,
    # Create operations
    create_specification,
    create_specification_from_quote,  # Feature #74
    # Read operations
    get_specification,
    get_specification_by_quote,
    get_specifications_by_status,
    get_all_specifications,
    get_specifications_with_details,
    count_specifications_by_status,
    specification_exists_for_quote,
    # Update operations
    update_specification,
    update_specification_status,
    set_signed_scan_url,
    # Delete operations
    delete_specification,
    # Utility functions
    generate_specification_number,
    get_specification_stats,
    get_specifications_for_signing,
    get_recently_signed_specifications,
)
from .deal_service import (
    # Data class
    Deal,
    CreateDealFromSpecResult,  # Feature #76
    # Constants
    DEAL_STATUSES,
    DEAL_STATUS_NAMES,
    DEAL_STATUS_COLORS,
    DEAL_TRANSITIONS,
    # Status helpers
    get_deal_status_name,
    get_deal_status_color,
    can_transition_deal,
    get_allowed_deal_transitions,
    is_deal_terminal,
    # Create operations
    create_deal,
    create_deal_from_specification,  # Feature #76
    # Read operations
    get_deal,
    get_deal_by_specification,
    get_deal_by_quote,
    get_deals_by_status,
    get_all_deals,
    get_deals_with_details,
    count_deals_by_status,
    deal_exists_for_specification,
    deal_exists_for_quote,
    # Update operations
    update_deal,
    update_deal_status,
    complete_deal,
    cancel_deal,
    update_deal_amount,
    # Delete operations
    delete_deal,
    # Utility functions
    generate_deal_number,
    get_deal_stats,
    get_active_deals,
    get_recent_deals,
    get_deals_by_date_range,
    search_deals,
)
from .plan_fact_service import (
    # Data classes
    PlanFactCategory,
    PlanFactItem,
    GeneratePlanFactResult,  # Feature #82 (DEAL-002)
    RegisterPaymentResult,  # Feature DEAL-003
    # Category functions
    get_all_categories,
    get_category,
    get_category_by_code,
    get_income_categories,
    get_expense_categories,
    # Create operations
    create_plan_fact_item,
    create_plan_fact_item_with_category_code,
    bulk_create_plan_fact_items,
    # Read operations
    get_plan_fact_item,
    get_plan_fact_items_for_deal,
    get_plan_fact_items_by_category,
    get_unpaid_items_for_deal,
    get_paid_items_for_deal,
    get_overdue_items_for_deal,
    count_items_for_deal,
    # Update operations
    update_plan_fact_item,
    record_actual_payment,
    clear_actual_payment,
    update_planned_payment,
    # Delete operations
    delete_plan_fact_item,
    delete_all_items_for_deal,
    # Summary and statistics
    get_deal_plan_fact_summary,
    get_items_grouped_by_category,
    get_upcoming_payments,
    get_payments_for_period,
    # Validation
    validate_item_for_payment,
    validate_deal_plan_fact,
    # Auto-generation functions (Feature DEAL-002)
    generate_plan_fact_from_deal,
    regenerate_plan_fact_for_deal,
    get_plan_fact_generation_preview,
    # Actual payment registration (Feature DEAL-003)
    SUPPORTED_PAYMENT_CURRENCIES,
    validate_payment_amount,
    validate_payment_date,
    validate_payment_currency,
    validate_payment_document,
    validate_payment_data,
    register_payment_for_item,
    register_partial_payment,
    bulk_register_payments,
    get_payment_registration_preview,
    get_variance_summary,
)
from .idn_service import (
    # Data classes (Feature #IDN-001, #IDN-002)
    ParsedQuoteIDN,
    ParsedItemIDN,
    IDNGenerationResult,
    # Parsing functions
    parse_quote_idn,
    parse_item_idn,
    # Validation functions
    is_valid_quote_idn,
    is_valid_item_idn,
    validate_seller_code,
    validate_inn,
    # Quote IDN generation (Feature #IDN-001)
    generate_quote_idn,
    assign_idn_to_quote,
    get_quote_idn,
    get_quote_by_idn,
    # Item IDN generation (Feature #IDN-002)
    generate_item_idn,
    regenerate_item_idns_for_quote,
    get_item_idn,
    get_item_by_idn,
    # Utility functions
    extract_quote_idn_from_item_idn,
    format_item_position,
    get_year_from_idn,
    get_customer_inn_from_idn,
    get_seller_code_from_idn,
    get_next_expected_sequence,
)
from .supplier_service import (
    # Data class (Feature #API-001)
    Supplier,
    # Validation functions
    validate_supplier_code,
    validate_inn as validate_supplier_inn,
    validate_kpp,
    # Create operations
    create_supplier,
    # Read operations
    get_supplier,
    get_supplier_by_code,
    get_all_suppliers,
    get_suppliers_by_country,
    count_suppliers,
    search_suppliers,
    get_active_suppliers,
    supplier_exists,
    # Update operations
    update_supplier,
    activate_supplier,
    deactivate_supplier,
    # Delete operations
    delete_supplier,
    # Utility functions
    get_unique_countries,
    get_supplier_stats,
    get_supplier_display_name,
    format_supplier_for_dropdown,
    get_suppliers_for_dropdown,
)
from .buyer_company_service import (
    # Data class (Feature #API-002)
    BuyerCompany,
    # Validation functions
    validate_company_code as validate_buyer_company_code,
    validate_inn as validate_buyer_inn,
    validate_kpp as validate_buyer_kpp,
    validate_ogrn,
    # Create operations
    create_buyer_company,
    # Read operations
    get_buyer_company,
    get_buyer_company_by_code,
    get_buyer_company_by_inn,
    get_all_buyer_companies,
    count_buyer_companies,
    search_buyer_companies,
    get_active_buyer_companies,
    buyer_company_exists,
    # Update operations
    update_buyer_company,
    activate_buyer_company,
    deactivate_buyer_company,
    # Delete operations
    delete_buyer_company,
    # Utility functions
    get_buyer_company_stats,
    get_buyer_company_display_name,
    format_buyer_company_for_dropdown,
    get_buyer_companies_for_dropdown,
    get_buyer_company_for_document,
)
from .seller_company_service import (
    # Data class (Feature #API-003)
    SellerCompany,
    # Validation functions
    validate_supplier_code as validate_seller_supplier_code,
    validate_inn as validate_seller_inn,
    validate_kpp as validate_seller_kpp,
    validate_ogrn as validate_seller_ogrn,
    # Create operations
    create_seller_company,
    # Read operations
    get_seller_company,
    get_seller_company_by_code,
    get_seller_company_by_inn,
    get_all_seller_companies,
    count_seller_companies,
    search_seller_companies,
    get_active_seller_companies,
    seller_company_exists,
    # Update operations
    update_seller_company,
    activate_seller_company,
    deactivate_seller_company,
    # Delete operations
    delete_seller_company,
    # Utility functions
    get_seller_company_stats,
    get_seller_company_display_name,
    format_seller_company_for_dropdown,
    get_seller_companies_for_dropdown,
    get_seller_company_for_document,
    get_seller_company_for_idn,
    get_unique_countries as get_seller_unique_countries,
)
from .customer_service import (
    # Data classes (Feature #API-004)
    Customer,
    CustomerContact,
    # Validation functions
    validate_inn as validate_customer_inn,
    validate_kpp as validate_customer_kpp,
    validate_ogrn as validate_customer_ogrn,
    validate_email,
    validate_phone,
    # Customer CRUD
    create_customer,
    get_customer,
    get_customer_with_contacts,
    get_customer_by_inn,
    get_all_customers,
    get_active_customers,
    count_customers,
    search_customers,
    customer_exists,
    update_customer,
    activate_customer,
    deactivate_customer,
    add_warehouse_address,
    remove_warehouse_address,
    delete_customer,
    # Contact CRUD
    create_contact,
    get_contact,
    get_contacts_for_customer,
    get_signatory_contact,
    get_primary_contact,
    count_contacts,
    update_contact,
    set_signatory,
    set_primary,
    delete_contact,
    delete_all_contacts,
    # Utility functions
    get_customer_stats,
    get_customer_display_name,
    format_customer_for_dropdown,
    get_customers_for_dropdown,
    get_customer_for_document,
    get_customer_for_idn,
    get_signatory_for_specification,
)
from .customer_contract_service import (
    # Data class (Feature #API-005)
    CustomerContract,
    # Constants
    CONTRACT_STATUSES,
    CONTRACT_STATUS_NAMES,
    CONTRACT_STATUS_COLORS,
    # Validation functions
    validate_contract_number,
    validate_contract_status,
    # Status helpers
    get_contract_status_name,
    get_contract_status_color,
    is_contract_active,
    # Create operations
    create_contract,
    # Read operations
    get_contract,
    get_contract_with_customer,
    get_contract_by_number,
    get_contracts_for_customer,
    get_active_contracts_for_customer,
    get_all_contracts,
    get_contracts_with_customer_names,
    count_contracts,
    search_contracts as search_customer_contracts,
    contract_exists,
    # Update operations
    update_contract,
    suspend_contract,
    terminate_contract,
    activate_contract as activate_customer_contract,
    # Specification numbering
    get_next_specification_number,
    get_current_specification_number,
    reset_specification_number,
    # Delete operations
    delete_contract,
    # Utility functions
    get_contract_stats,
    get_contract_display_name,
    format_contract_for_dropdown,
    get_contracts_for_dropdown,
    get_contract_for_specification,
)
from .location_service import (
    # Data class (Feature #API-006)
    Location,
    # Validation functions
    validate_location_code,
    validate_country,
    # Create operations
    create_location,
    create_location_if_not_exists,
    # Read operations
    get_location,
    get_location_by_code,
    get_location_by_country_city,
    get_all_locations,
    get_locations_by_country,
    get_hub_locations,
    get_customs_point_locations,
    count_locations,
    location_exists,
    # Search operations (for HTMX dropdown)
    search_locations,
    get_active_locations,
    # Update operations
    update_location,
    activate_location,
    deactivate_location,
    set_as_hub,
    set_as_customs_point,
    # Delete operations
    delete_location,
    # Utility functions
    get_unique_countries as get_location_unique_countries,
    get_location_stats,
    get_location_display_name,
    format_location_for_dropdown,
    get_locations_for_dropdown,
    # Seed data
    seed_default_locations,
    get_location_for_route,
)
from .brand_supplier_assignment_service import (
    # Data class (Feature #API-008)
    BrandSupplierAssignment,
    # Create operations
    create_brand_supplier_assignment,
    bulk_create_brand_supplier_assignments,
    # Read operations
    get_brand_supplier_assignment,
    get_assignments_for_brand,
    get_primary_supplier_for_brand,
    get_assignments_for_supplier,
    get_all_brand_supplier_assignments,
    count_brand_supplier_assignments,
    get_unique_assigned_brands,
    brand_has_supplier,
    brand_has_primary_supplier,
    # Update operations
    update_brand_supplier_assignment,
    set_primary_supplier_for_brand,
    unset_primary_supplier_for_brand,
    # Delete operations
    delete_brand_supplier_assignment,
    delete_brand_supplier_assignment_by_brand_supplier,
    delete_all_assignments_for_brand,
    delete_all_assignments_for_supplier,
    # Utility functions
    get_brand_supplier_mapping,
    get_suppliers_count_by_brand,
    get_brands_without_supplier,
    get_brands_without_primary_supplier,
    get_brand_supplier_assignment_stats,
    format_brand_supplier_for_display,
    get_suppliers_for_brand_dropdown,
)
from .route_logistics_assignment_service import (
    # Data class (Feature #API-009)
    RouteLogisticsAssignment,
    # Validation functions
    validate_route_pattern,
    parse_route_pattern,
    build_route_pattern,
    normalize_route_pattern,
    # Create operations
    create_route_logistics_assignment,
    bulk_create_route_logistics_assignments,
    # Read operations
    get_route_logistics_assignment,
    get_route_logistics_assignment_by_pattern,
    get_assignments_for_user,
    get_all_route_logistics_assignments,
    count_route_logistics_assignments,
    get_unique_route_patterns,
    get_unique_origins,
    get_unique_destinations,
    assignment_exists,
    # Route matching functions
    match_route_to_logistics_manager,
    get_logistics_manager_for_locations,
    find_matching_routes,
    # Update operations
    update_route_logistics_assignment,
    reassign_route_to_user,
    # Delete operations
    delete_route_logistics_assignment,
    delete_route_logistics_assignment_by_pattern,
    delete_all_assignments_for_user,
    # Utility functions
    get_route_user_mapping,
    get_routes_count_by_user,
    get_route_logistics_assignment_stats,
    get_route_assignments_summary,
    format_route_assignment_for_display,
    get_routes_for_dropdown,
    check_route_coverage,
    get_uncovered_routes,
)
from .supplier_invoice_service import (
    # Data classes (Feature #API-010)
    SupplierInvoice,
    SupplierInvoiceItem,
    InvoiceSummary,
    QuoteInvoicingItem,
    QuoteInvoicingSummary,
    # Constants
    INVOICE_STATUS_PENDING,
    INVOICE_STATUS_PARTIALLY_PAID,
    INVOICE_STATUS_PAID,
    INVOICE_STATUS_OVERDUE,
    INVOICE_STATUS_CANCELLED,
    INVOICE_STATUSES,
    INVOICE_STATUS_NAMES,
    INVOICE_STATUS_COLORS,
    DEFAULT_CURRENCY,
    SUPPORTED_CURRENCIES,
    # Validation functions
    validate_invoice_number,
    validate_invoice_status,
    validate_currency,
    validate_amount,
    # Status helpers
    get_invoice_status_name,
    get_invoice_status_color,
    is_invoice_payable,
    is_invoice_editable,
    # Invoice create operations
    create_invoice,
    create_invoice_with_items,
    # Invoice read operations
    get_invoice,
    get_invoice_with_details,
    get_invoice_by_number,
    get_invoices_for_supplier,
    get_all_invoices,
    count_invoices,
    search_invoices,
    invoice_exists,
    get_overdue_invoices,
    get_pending_invoices,
    # Invoice update operations
    update_invoice,
    update_invoice_status,
    cancel_invoice,
    mark_invoice_overdue,
    update_overdue_invoices,
    # Invoice delete operations
    delete_invoice,
    # Invoice item operations
    add_invoice_item,
    get_invoice_item,
    get_invoice_items,
    get_invoice_items_with_details,
    update_invoice_item,
    delete_invoice_item,
    get_items_for_quote_item,
    get_total_invoiced_for_quote_item,
    get_quote_invoicing_summary,
    # Utility functions
    get_invoice_summary,
    get_invoice_stats_by_supplier,
    format_invoice_for_display,
    get_invoices_for_dropdown,
)
from .supplier_invoice_payment_service import (
    # Data classes (Feature #API-011)
    SupplierInvoicePayment,
    PaymentSummary,
    SupplierPaymentSummary,
    BuyerCompanyPaymentSummary,
    # Constants
    PAYMENT_TYPE_ADVANCE,
    PAYMENT_TYPE_PARTIAL,
    PAYMENT_TYPE_FINAL,
    PAYMENT_TYPE_REFUND,
    PAYMENT_TYPES,
    PAYMENT_TYPE_NAMES,
    PAYMENT_TYPE_COLORS,
    # Validation functions
    validate_payment_type,
    validate_payment_amount,
    validate_exchange_rate,
    validate_payment_document,
    # Payment type helpers
    get_payment_type_name,
    get_payment_type_color,
    is_refund,
    is_advance,
    is_final_payment,
    # Create operations
    register_payment,
    register_advance_payment,
    register_final_payment,
    register_refund,
    # Read operations
    get_payment,
    get_payment_with_details,
    get_payments_for_invoice,
    get_payments_for_invoice_with_details,
    get_all_payments,
    count_payments,
    get_recent_payments,
    get_payments_by_buyer_company,
    get_refunds_for_invoice,
    # Update operations
    update_payment,
    update_payment_document,
    update_payment_exchange_rate,
    # Delete operations
    delete_payment,
    delete_all_payments_for_invoice,
    # Summary and statistics
    get_invoice_payment_summary,
    get_supplier_payment_summary,
    get_payments_summary_by_buyer_company,
    get_payment_stats,
    # Utility functions
    get_remaining_amount,
    is_invoice_fully_paid,
    format_payment_for_display,
    get_payments_for_display,
)
from .telegram_service import (
    # Configuration
    is_bot_configured,
    get_bot,
    # Notification types
    NotificationType,
    NotificationPayload,
    # Message functions
    format_notification,
    send_message,
    send_notification,
    send_approval_request,
    edit_message,
    # Keyboard builders
    build_approval_keyboard,
    build_open_quote_keyboard,
    # Webhook management
    setup_webhook,
    delete_webhook,
    get_webhook_info,
    # Bot info
    get_bot_info,
    # Callback data
    CallbackData,
    parse_callback_data,
    # Webhook processing (Feature #53)
    WebhookResult,
    parse_telegram_update,
    process_webhook_update,
    respond_to_command,
    # Account verification (Feature #55)
    VerificationResult,
    verify_telegram_account,
    get_telegram_user,
    is_telegram_linked,
    # Verification code UI (Feature #56)
    TelegramStatus,
    get_user_telegram_status,
    request_verification_code,
    unlink_telegram_account,
    # Status command (Feature #57)
    UserTask,
    get_user_tasks,
    handle_status_command,
    # Task assigned notification (Feature #58)
    TaskAssignedNotification,
    get_user_telegram_id,
    record_notification,
    send_task_assigned_notification,
    notify_users_of_task_assignment,
    notify_role_users_of_task,
    # Approval required notification (Feature #59)
    ApprovalRequiredNotification,
    send_approval_required_notification,
    send_approval_notification_for_quote,
    # Approve callback handler (Feature #60)
    ApprovalCallbackResult,
    handle_approve_callback,
    send_callback_response,
    # Reject callback handler (Feature #61)
    handle_reject_callback,
    # Status changed notification (Feature #62)
    StatusChangedNotification,
    send_status_changed_notification,
    notify_quote_creator_of_status_change,
    notify_assigned_users_of_status_change,
    # Returned for revision notification (Feature #63)
    ReturnedForRevisionNotification,
    send_returned_for_revision_notification,
    notify_creator_of_return,
)

__all__ = [
    # Database
    "get_supabase",
    "get_anon_client",
    # Export
    "fetch_export_data",
    "ExportData",
    "generate_specification_pdf",
    "generate_invoice_pdf",
    "create_validation_excel",
    # Versioning
    "create_quote_version",
    "list_quote_versions",
    "get_quote_version",
    # Roles
    "Role",
    "UserRole",
    "get_user_roles",
    "get_user_role_codes",
    "has_role",
    "has_any_role",
    "has_all_roles",
    "assign_role",
    "remove_role",
    "get_all_roles",
    "get_role_by_code",
    "get_users_by_role",
    "get_users_by_any_role",
    # Route protection middleware
    "require_role",
    "require_any_role",
    "require_all_roles",
    "get_session_user_roles",
    # Brand assignments (Feature #30)
    "BrandAssignment",
    "create_brand_assignment",
    "upsert_brand_assignment",
    "bulk_create_assignments",
    "get_brand_assignment",
    "get_brand_assignment_by_brand",
    "get_all_brand_assignments",
    "get_user_brand_assignments",
    "get_assignments_with_user_details",
    "update_brand_assignment",
    "reassign_brand",
    "delete_brand_assignment",
    "delete_brand_assignment_by_brand",
    "delete_all_user_assignments",
    "get_procurement_manager",
    "get_assigned_brands",
    "get_unique_brands_in_org",
    "get_unassigned_brands",
    "get_brand_manager_mapping",
    "count_assignments_by_user",
    "is_brand_assigned",
    # Workflow
    "WorkflowStatus",
    "StatusTransition",
    "TransitionResult",
    "STATUS_NAMES",
    "STATUS_NAMES_SHORT",
    "STATUS_COLORS",
    "IN_PROGRESS_STATUSES",
    "FINAL_STATUSES",
    "ALLOWED_TRANSITIONS",
    "get_status_name",
    "get_status_name_short",
    "get_status_color",
    "get_allowed_transitions",
    "get_allowed_target_statuses",
    "can_transition",
    "is_final_status",
    "is_in_progress",
    "get_workflow_order",
    "get_workflow_stage",
    "get_all_statuses",
    # Permission matrix functions (Feature #24)
    "get_transition_requirements",
    "get_roles_for_transition",
    "get_transitions_by_role",
    "get_permission_matrix",
    "get_permission_matrix_detailed",
    "get_outgoing_transitions",
    "get_incoming_transitions",
    "is_comment_required",
    "is_auto_transition",
    # Transition execution functions (Feature #25)
    "transition_quote_status",
    "get_quote_workflow_status",
    "get_quote_transition_history",
    "get_available_transitions_for_quote",
    # Auto-transition functions (Feature #28)
    "check_and_auto_transition_to_sales_review",
    "complete_logistics",
    "complete_customs",
    "get_parallel_stages_status",
    # Procurement assignment functions (Feature #29)
    "get_procurement_users_for_quote",
    "assign_procurement_users_to_quote",
    "transition_to_pending_procurement",
    "get_quote_procurement_status",
    # Telegram bot (Feature #52)
    "is_bot_configured",
    "get_bot",
    "NotificationType",
    "NotificationPayload",
    "format_notification",
    "send_message",
    "send_notification",
    "send_approval_request",
    "edit_message",
    "build_approval_keyboard",
    "build_open_quote_keyboard",
    "setup_webhook",
    "delete_webhook",
    "get_webhook_info",
    "get_bot_info",
    "CallbackData",
    "parse_callback_data",
    # Webhook processing (Feature #53)
    "WebhookResult",
    "parse_telegram_update",
    "process_webhook_update",
    "respond_to_command",
    # Account verification (Feature #55)
    "VerificationResult",
    "verify_telegram_account",
    "get_telegram_user",
    "is_telegram_linked",
    # Verification code UI (Feature #56)
    "TelegramStatus",
    "get_user_telegram_status",
    "request_verification_code",
    "unlink_telegram_account",
    # Status command (Feature #57)
    "UserTask",
    "get_user_tasks",
    "handle_status_command",
    # Task assigned notification (Feature #58)
    "TaskAssignedNotification",
    "get_user_telegram_id",
    "record_notification",
    "send_task_assigned_notification",
    "notify_users_of_task_assignment",
    "notify_role_users_of_task",
    # Approval required notification (Feature #59)
    "ApprovalRequiredNotification",
    "send_approval_required_notification",
    "send_approval_notification_for_quote",
    # Approve callback handler (Feature #60)
    "ApprovalCallbackResult",
    "handle_approve_callback",
    "send_callback_response",
    # Reject callback handler (Feature #61)
    "handle_reject_callback",
    # Status changed notification (Feature #62)
    "StatusChangedNotification",
    "send_status_changed_notification",
    "notify_quote_creator_of_status_change",
    "notify_assigned_users_of_status_change",
    # Returned for revision notification (Feature #63)
    "ReturnedForRevisionNotification",
    "send_returned_for_revision_notification",
    "notify_creator_of_return",
    # Approval service (Feature #64)
    "Approval",
    "create_approval",
    "create_approvals_for_role",
    "get_approval",
    "get_approval_by_quote",
    "get_approvals_for_quote",
    "get_pending_approval_for_quote",
    "get_pending_approvals_for_user",
    "get_approvals_requested_by",
    "get_approvals_with_details",
    "count_pending_approvals",
    "update_approval_status",
    "approve_quote_approval",
    "reject_quote_approval",
    "cancel_pending_approvals_for_quote",
    "has_pending_approval",
    "get_latest_approval_decision",
    "get_approval_stats_for_user",
    # High-level workflow functions (Feature #65, #66)
    "ApprovalRequestResult",
    "request_approval",
    "ApprovalDecisionResult",
    "process_approval_decision",
    # Specification service (Feature #73)
    "Specification",
    "SPEC_STATUSES",
    "SPEC_STATUS_NAMES",
    "SPEC_STATUS_COLORS",
    "SPEC_TRANSITIONS",
    "get_spec_status_name",
    "get_spec_status_color",
    "can_transition_spec",
    "get_allowed_spec_transitions",
    "create_specification",
    "get_specification",
    "get_specification_by_quote",
    "get_specifications_by_status",
    "get_all_specifications",
    "get_specifications_with_details",
    "count_specifications_by_status",
    "specification_exists_for_quote",
    "update_specification",
    "update_specification_status",
    "set_signed_scan_url",
    "delete_specification",
    "generate_specification_number",
    "get_specification_stats",
    "get_specifications_for_signing",
    "get_recently_signed_specifications",
    # Create from quote (Feature #74)
    "CreateSpecFromQuoteResult",
    "create_specification_from_quote",
    # Deal service (Feature #75)
    "Deal",
    "DEAL_STATUSES",
    "DEAL_STATUS_NAMES",
    "DEAL_STATUS_COLORS",
    "DEAL_TRANSITIONS",
    "get_deal_status_name",
    "get_deal_status_color",
    "can_transition_deal",
    "get_allowed_deal_transitions",
    "is_deal_terminal",
    "create_deal",
    "get_deal",
    "get_deal_by_specification",
    "get_deal_by_quote",
    "get_deals_by_status",
    "get_all_deals",
    "get_deals_with_details",
    "count_deals_by_status",
    "deal_exists_for_specification",
    "deal_exists_for_quote",
    "update_deal",
    "update_deal_status",
    "complete_deal",
    "cancel_deal",
    "update_deal_amount",
    "delete_deal",
    "generate_deal_number",
    "get_deal_stats",
    "get_active_deals",
    "get_recent_deals",
    "get_deals_by_date_range",
    "search_deals",
    # Create deal from spec (Feature #76)
    "CreateDealFromSpecResult",
    "create_deal_from_specification",
    # Plan-fact service (Feature #81)
    "PlanFactCategory",
    "PlanFactItem",
    # Category functions
    "get_all_categories",
    "get_category",
    "get_category_by_code",
    "get_income_categories",
    "get_expense_categories",
    # Plan-fact create operations
    "create_plan_fact_item",
    "create_plan_fact_item_with_category_code",
    "bulk_create_plan_fact_items",
    # Plan-fact read operations
    "get_plan_fact_item",
    "get_plan_fact_items_for_deal",
    "get_plan_fact_items_by_category",
    "get_unpaid_items_for_deal",
    "get_paid_items_for_deal",
    "get_overdue_items_for_deal",
    "count_items_for_deal",
    # Plan-fact update operations
    "update_plan_fact_item",
    "record_actual_payment",
    "clear_actual_payment",
    "update_planned_payment",
    # Plan-fact delete operations
    "delete_plan_fact_item",
    "delete_all_items_for_deal",
    # Plan-fact summary and statistics
    "get_deal_plan_fact_summary",
    "get_items_grouped_by_category",
    "get_upcoming_payments",
    "get_payments_for_period",
    # Plan-fact validation
    "validate_item_for_payment",
    "validate_deal_plan_fact",
    # Auto-generation functions (Feature DEAL-002)
    "GeneratePlanFactResult",
    "generate_plan_fact_from_deal",
    "regenerate_plan_fact_for_deal",
    "get_plan_fact_generation_preview",
    # Actual payment registration (Feature DEAL-003)
    "RegisterPaymentResult",
    "SUPPORTED_PAYMENT_CURRENCIES",
    "validate_payment_amount",
    "validate_payment_date",
    "validate_payment_currency",
    "validate_payment_document",
    "validate_payment_data",
    "register_payment_for_item",
    "register_partial_payment",
    "bulk_register_payments",
    "get_payment_registration_preview",
    "get_variance_summary",
    # IDN service (Feature #IDN-001, #IDN-002)
    "ParsedQuoteIDN",
    "ParsedItemIDN",
    "IDNGenerationResult",
    "parse_quote_idn",
    "parse_item_idn",
    "is_valid_quote_idn",
    "is_valid_item_idn",
    "validate_seller_code",
    "validate_inn",
    "generate_quote_idn",
    "assign_idn_to_quote",
    "get_quote_idn",
    "get_quote_by_idn",
    "generate_item_idn",
    "regenerate_item_idns_for_quote",
    "get_item_idn",
    "get_item_by_idn",
    "extract_quote_idn_from_item_idn",
    "format_item_position",
    "get_year_from_idn",
    "get_customer_inn_from_idn",
    "get_seller_code_from_idn",
    "get_next_expected_sequence",
    # Supplier service (Feature #API-001)
    "Supplier",
    "validate_supplier_code",
    "validate_supplier_inn",
    "validate_kpp",
    "create_supplier",
    "get_supplier",
    "get_supplier_by_code",
    "get_all_suppliers",
    "get_suppliers_by_country",
    "count_suppliers",
    "search_suppliers",
    "get_active_suppliers",
    "supplier_exists",
    "update_supplier",
    "activate_supplier",
    "deactivate_supplier",
    "delete_supplier",
    "get_unique_countries",
    "get_supplier_stats",
    "get_supplier_display_name",
    "format_supplier_for_dropdown",
    "get_suppliers_for_dropdown",
    # Buyer company service (Feature #API-002)
    "BuyerCompany",
    "validate_buyer_company_code",
    "validate_buyer_inn",
    "validate_buyer_kpp",
    "validate_ogrn",
    "create_buyer_company",
    "get_buyer_company",
    "get_buyer_company_by_code",
    "get_buyer_company_by_inn",
    "get_all_buyer_companies",
    "count_buyer_companies",
    "search_buyer_companies",
    "get_active_buyer_companies",
    "buyer_company_exists",
    "update_buyer_company",
    "activate_buyer_company",
    "deactivate_buyer_company",
    "delete_buyer_company",
    "get_buyer_company_stats",
    "get_buyer_company_display_name",
    "format_buyer_company_for_dropdown",
    "get_buyer_companies_for_dropdown",
    "get_buyer_company_for_document",
    # Seller company service (Feature #API-003)
    "SellerCompany",
    "validate_seller_supplier_code",
    "validate_seller_inn",
    "validate_seller_kpp",
    "validate_seller_ogrn",
    "create_seller_company",
    "get_seller_company",
    "get_seller_company_by_code",
    "get_seller_company_by_inn",
    "get_all_seller_companies",
    "count_seller_companies",
    "search_seller_companies",
    "get_active_seller_companies",
    "seller_company_exists",
    "update_seller_company",
    "activate_seller_company",
    "deactivate_seller_company",
    "delete_seller_company",
    "get_seller_company_stats",
    "get_seller_company_display_name",
    "format_seller_company_for_dropdown",
    "get_seller_companies_for_dropdown",
    "get_seller_company_for_document",
    "get_seller_company_for_idn",
    "get_seller_unique_countries",
    # Customer service (Feature #API-004)
    "Customer",
    "CustomerContact",
    "validate_customer_inn",
    "validate_customer_kpp",
    "validate_customer_ogrn",
    "validate_email",
    "validate_phone",
    "create_customer",
    "get_customer",
    "get_customer_with_contacts",
    "get_customer_by_inn",
    "get_all_customers",
    "get_active_customers",
    "count_customers",
    "search_customers",
    "customer_exists",
    "update_customer",
    "activate_customer",
    "deactivate_customer",
    "add_warehouse_address",
    "remove_warehouse_address",
    "delete_customer",
    "create_contact",
    "get_contact",
    "get_contacts_for_customer",
    "get_signatory_contact",
    "get_primary_contact",
    "count_contacts",
    "update_contact",
    "set_signatory",
    "set_primary",
    "delete_contact",
    "delete_all_contacts",
    "get_customer_stats",
    "get_customer_display_name",
    "format_customer_for_dropdown",
    "get_customers_for_dropdown",
    "get_customer_for_document",
    "get_customer_for_idn",
    "get_signatory_for_specification",
    # Customer contract service (Feature #API-005)
    "CustomerContract",
    "CONTRACT_STATUSES",
    "CONTRACT_STATUS_NAMES",
    "CONTRACT_STATUS_COLORS",
    "validate_contract_number",
    "validate_contract_status",
    "get_contract_status_name",
    "get_contract_status_color",
    "is_contract_active",
    "create_contract",
    "get_contract",
    "get_contract_with_customer",
    "get_contract_by_number",
    "get_contracts_for_customer",
    "get_active_contracts_for_customer",
    "get_all_contracts",
    "get_contracts_with_customer_names",
    "count_contracts",
    "search_customer_contracts",
    "contract_exists",
    "update_contract",
    "suspend_contract",
    "terminate_contract",
    "activate_customer_contract",
    "get_next_specification_number",
    "get_current_specification_number",
    "reset_specification_number",
    "delete_contract",
    "get_contract_stats",
    "get_contract_display_name",
    "format_contract_for_dropdown",
    "get_contracts_for_dropdown",
    "get_contract_for_specification",
    # Location service (Feature #API-006)
    "Location",
    "validate_location_code",
    "validate_country",
    "create_location",
    "create_location_if_not_exists",
    "get_location",
    "get_location_by_code",
    "get_location_by_country_city",
    "get_all_locations",
    "get_locations_by_country",
    "get_hub_locations",
    "get_customs_point_locations",
    "count_locations",
    "location_exists",
    "search_locations",
    "get_active_locations",
    "update_location",
    "activate_location",
    "deactivate_location",
    "set_as_hub",
    "set_as_customs_point",
    "delete_location",
    "get_location_unique_countries",
    "get_location_stats",
    "get_location_display_name",
    "format_location_for_dropdown",
    "get_locations_for_dropdown",
    "seed_default_locations",
    "get_location_for_route",
    # Brand supplier assignment service (Feature #API-008)
    "BrandSupplierAssignment",
    "create_brand_supplier_assignment",
    "bulk_create_brand_supplier_assignments",
    "get_brand_supplier_assignment",
    "get_assignments_for_brand",
    "get_primary_supplier_for_brand",
    "get_assignments_for_supplier",
    "get_all_brand_supplier_assignments",
    "count_brand_supplier_assignments",
    "get_unique_assigned_brands",
    "brand_has_supplier",
    "brand_has_primary_supplier",
    "update_brand_supplier_assignment",
    "set_primary_supplier_for_brand",
    "unset_primary_supplier_for_brand",
    "delete_brand_supplier_assignment",
    "delete_brand_supplier_assignment_by_brand_supplier",
    "delete_all_assignments_for_brand",
    "delete_all_assignments_for_supplier",
    "get_brand_supplier_mapping",
    "get_suppliers_count_by_brand",
    "get_brands_without_supplier",
    "get_brands_without_primary_supplier",
    "get_brand_supplier_assignment_stats",
    "format_brand_supplier_for_display",
    "get_suppliers_for_brand_dropdown",
    # Route logistics assignment service (Feature #API-009)
    "RouteLogisticsAssignment",
    "validate_route_pattern",
    "parse_route_pattern",
    "build_route_pattern",
    "normalize_route_pattern",
    "create_route_logistics_assignment",
    "bulk_create_route_logistics_assignments",
    "get_route_logistics_assignment",
    "get_route_logistics_assignment_by_pattern",
    "get_assignments_for_user",
    "get_all_route_logistics_assignments",
    "count_route_logistics_assignments",
    "get_unique_route_patterns",
    "get_unique_origins",
    "get_unique_destinations",
    "assignment_exists",
    "match_route_to_logistics_manager",
    "get_logistics_manager_for_locations",
    "find_matching_routes",
    "update_route_logistics_assignment",
    "reassign_route_to_user",
    "delete_route_logistics_assignment",
    "delete_route_logistics_assignment_by_pattern",
    "delete_all_assignments_for_user",
    "get_route_user_mapping",
    "get_routes_count_by_user",
    "get_route_logistics_assignment_stats",
    "get_route_assignments_summary",
    "format_route_assignment_for_display",
    "get_routes_for_dropdown",
    "check_route_coverage",
    "get_uncovered_routes",
    # Supplier invoice service (Feature #API-010)
    "SupplierInvoice",
    "SupplierInvoiceItem",
    "InvoiceSummary",
    "INVOICE_STATUS_PENDING",
    "INVOICE_STATUS_PARTIALLY_PAID",
    "INVOICE_STATUS_PAID",
    "INVOICE_STATUS_OVERDUE",
    "INVOICE_STATUS_CANCELLED",
    "INVOICE_STATUSES",
    "INVOICE_STATUS_NAMES",
    "INVOICE_STATUS_COLORS",
    "DEFAULT_CURRENCY",
    "SUPPORTED_CURRENCIES",
    "validate_invoice_number",
    "validate_invoice_status",
    "validate_currency",
    "validate_amount",
    "get_invoice_status_name",
    "get_invoice_status_color",
    "is_invoice_payable",
    "is_invoice_editable",
    "create_invoice",
    "create_invoice_with_items",
    "get_invoice",
    "get_invoice_with_details",
    "get_invoice_by_number",
    "get_invoices_for_supplier",
    "get_all_invoices",
    "count_invoices",
    "search_invoices",
    "invoice_exists",
    "get_overdue_invoices",
    "get_pending_invoices",
    "update_invoice",
    "update_invoice_status",
    "cancel_invoice",
    "mark_invoice_overdue",
    "update_overdue_invoices",
    "delete_invoice",
    "add_invoice_item",
    "get_invoice_item",
    "get_invoice_items",
    "get_invoice_items_with_details",
    "update_invoice_item",
    "delete_invoice_item",
    "get_items_for_quote_item",
    "get_total_invoiced_for_quote_item",
    "get_invoice_summary",
    "get_invoice_stats_by_supplier",
    "format_invoice_for_display",
    "get_invoices_for_dropdown",
    # Supplier invoice payment service (Feature #API-011)
    "SupplierInvoicePayment",
    "PaymentSummary",
    "SupplierPaymentSummary",
    "BuyerCompanyPaymentSummary",
    "PAYMENT_TYPE_ADVANCE",
    "PAYMENT_TYPE_PARTIAL",
    "PAYMENT_TYPE_FINAL",
    "PAYMENT_TYPE_REFUND",
    "PAYMENT_TYPES",
    "PAYMENT_TYPE_NAMES",
    "PAYMENT_TYPE_COLORS",
    "validate_payment_type",
    "validate_payment_amount",
    "validate_exchange_rate",
    "validate_payment_document",
    "get_payment_type_name",
    "get_payment_type_color",
    "is_refund",
    "is_advance",
    "is_final_payment",
    "register_payment",
    "register_advance_payment",
    "register_final_payment",
    "register_refund",
    "get_payment",
    "get_payment_with_details",
    "get_payments_for_invoice",
    "get_payments_for_invoice_with_details",
    "get_all_payments",
    "count_payments",
    "get_recent_payments",
    "get_payments_by_buyer_company",
    "get_refunds_for_invoice",
    "update_payment",
    "update_payment_document",
    "update_payment_exchange_rate",
    "delete_payment",
    "delete_all_payments_for_invoice",
    "get_invoice_payment_summary",
    "get_supplier_payment_summary",
    "get_payments_summary_by_buyer_company",
    "get_payment_stats",
    "get_remaining_amount",
    "is_invoice_fully_paid",
    "format_payment_for_display",
    "get_payments_for_display",
]
