"""Static schema-drift lint for Supabase-style `.select(...)` calls.

Walks the Python AST of given files (or default `api/*.py + services/*.py`),
extracts every `.select(<literal>)` call on a Supabase chain, identifies the
table from the nearest preceding `.table(...)` / `.from_(...)` call, then
diffs the requested columns against the live schema parsed from the
auto-generated TypeScript file ``frontend/src/shared/types/database.types.ts``.

Outputs violations in the form ``{file}:{line}: column 'X' not in kvota.Y``
and exits 1 when any are found. Cases that cannot be statically resolved
(unknown chain shape, dynamic select arg) emit WARNINGs but do NOT fail.

Designed for Phase 1b of the customs Phase B hotfix plan
(see ``docs/plans/2026-05-04-customs-phase-b-hotfix-plan.md`` AD-3).
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

# Repo conventions
REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_TYPES_PATHS = (
    "frontend/src/shared/types/database.types.ts",
    "frontend/src/database.types.ts",
)
DEFAULT_SCAN_GLOBS = ("api/*.py", "services/*.py")
SCHEMA_NAME = "kvota"

# A single Supabase column entry inside a `.select(...)` literal. Embed paths
# look like ``foo!inner(col1, col2)`` or ``foo(col1)`` — those are PostgREST
# joins that we DO NOT validate against the parent table; we only check the
# top-level columns. We strip embeds before column-checking.
#
# Also matches aliased embeds: ``alias:tablename!inner(col1)`` and
# ``alias:tablename(col1)``. The colon prefix is optional.
_EMBED_RE = re.compile(r"(?:\w+:)?\w+(?:![a-zA-Z]+)?\s*\(")


def parse_database_types(path: Path) -> dict[str, set[str]]:
    """Parse ``database.types.ts`` and return ``{table_name: set(columns)}``.

    The file is auto-generated by ``supabase gen types`` and follows a stable
    pattern::

        export type Database = {
          kvota: {
            Tables: {
              <tableName>: {
                Row: {
                  <colName>: <tsType>
                  ...
                }
                Insert: { ... }
                Update: { ... }
                Relationships: [ ... ]
              }
              ...
            }
            Views: { ... }
            Functions: { ... }
            ...
          }
        }

    We extract only the ``Row`` block of each table inside the ``kvota``
    schema. Column names are identifiers; types may include ``Json``,
    ``Json | null``, etc., which we ignore — we only care about the keys.

    We track brace depth from the ``Row: {`` line so nested anonymous object
    literals (rare but possible) don't end the block prematurely.
    """
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    schema_dict: dict[str, set[str]] = {}

    # Locate ``  kvota: {`` (2-space indent, top-level under Database).
    schema_pat = re.compile(rf"^\s+{re.escape(SCHEMA_NAME)}:\s*\{{")
    schema_start = None
    for i, line in enumerate(lines):
        if schema_pat.match(line):
            schema_start = i
            break
    if schema_start is None:
        raise RuntimeError(
            f"Could not find ``{SCHEMA_NAME}: {{`` in {path}; "
            f"types file may be malformed."
        )

    # From schema_start, find ``Tables: {`` block.
    tables_start = None
    for i in range(schema_start + 1, len(lines)):
        if re.match(r"^\s+Tables:\s*\{", lines[i]):
            tables_start = i
            break
    if tables_start is None:
        raise RuntimeError(
            f"Could not find ``Tables: {{`` under ``{SCHEMA_NAME}`` in {path}."
        )

    # Now scan for ``<tableName>: {`` entries (table-level), then within each
    # find ``Row: {`` and capture identifiers until the matching closing ``}``.
    # We rely on the generator's consistent indentation.
    table_pat = re.compile(r"^\s{6}(\w+):\s*\{")  # 6-space indent for table name
    row_pat = re.compile(r"^\s+Row:\s*\{")
    col_pat = re.compile(r"^\s+(\w+)\??:\s*")  # ident, optional ?, colon

    i = tables_start + 1
    while i < len(lines):
        line = lines[i]
        # Stop if we've left the kvota.Tables block — heuristic: a 4-space
        # closing brace indicates the end of Tables.
        if re.match(r"^\s{4}\}", line):
            break
        m = table_pat.match(line)
        if not m:
            i += 1
            continue
        table_name = m.group(1)
        # Find ``Row: {`` within this table block.
        j = i + 1
        while j < len(lines) and not row_pat.match(lines[j]):
            # Bail if we hit another top-level table without finding Row.
            if table_pat.match(lines[j]):
                break
            j += 1
        if j >= len(lines) or not row_pat.match(lines[j]):
            # No Row block (shouldn't happen for kvota.Tables.*) — skip.
            i = j
            continue
        # Walk into the Row block, tracking brace depth so nested anonymous
        # object literals don't end us prematurely.
        depth = 1  # we just opened ``Row: {``
        cols: set[str] = set()
        k = j + 1
        while k < len(lines) and depth > 0:
            kline = lines[k]
            depth += kline.count("{") - kline.count("}")
            if depth == 0:
                break
            # A column declaration is at indent > row_indent and matches col_pat.
            cm = col_pat.match(kline)
            if cm and depth == 1:
                cols.add(cm.group(1))
            k += 1
        schema_dict[table_name] = cols
        i = k + 1
    return schema_dict


def find_types_file() -> Path:
    """Locate ``database.types.ts`` from the repo root."""
    for rel in DEFAULT_TYPES_PATHS:
        candidate = REPO_ROOT / rel
        if candidate.exists():
            return candidate
    raise FileNotFoundError(
        "database.types.ts not found in any of: "
        + ", ".join(DEFAULT_TYPES_PATHS)
    )


# --- Static value resolver -------------------------------------------------

def _try_resolve(node: ast.AST, env: dict[str, object]) -> object:
    """Best-effort static eval. Returns str | list[str] | None.

    Supports:
      - Constant string -> str
      - Tuple/List of Constant strings -> list[str]
      - JoinedStr (f-string) where every FormattedValue resolves -> str
      - BinOp ``+`` of resolvable parts -> str
      - ``", ".join(<resolvable iterable>)`` -> str (joined)
      - Name -> lookup in env
      - Starred(Name) inside iterables -> expanded list[str]
    Returns None when not resolvable.
    """
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, (ast.Tuple, ast.List)):
        out: list[str] = []
        for elt in node.elts:
            if isinstance(elt, ast.Starred):
                resolved = _try_resolve(elt.value, env)
                if isinstance(resolved, list):
                    out.extend(resolved)
                elif isinstance(resolved, str):
                    out.append(resolved)
                else:
                    return None
            else:
                resolved = _try_resolve(elt, env)
                if isinstance(resolved, list):
                    out.extend(resolved)
                elif isinstance(resolved, str):
                    out.append(resolved)
                else:
                    return None
        return out
    if isinstance(node, ast.Name):
        return env.get(node.id)
    if isinstance(node, ast.JoinedStr):
        parts: list[str] = []
        for v in node.values:
            if isinstance(v, ast.Constant) and isinstance(v.value, str):
                parts.append(v.value)
            elif isinstance(v, ast.FormattedValue):
                resolved = _try_resolve(v.value, env)
                if isinstance(resolved, str):
                    parts.append(resolved)
                elif isinstance(resolved, list):
                    parts.append(", ".join(resolved))
                else:
                    return None
            else:
                return None
        return "".join(parts)
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        left = _try_resolve(node.left, env)
        right = _try_resolve(node.right, env)
        if isinstance(left, str) and isinstance(right, str):
            return left + right
        return None
    if isinstance(node, ast.Call):
        # Handle ``", ".join(<iterable>)`` and bytes.join variants.
        func = node.func
        if (
            isinstance(func, ast.Attribute)
            and func.attr == "join"
            and isinstance(func.value, ast.Constant)
            and isinstance(func.value.value, str)
        ):
            sep = func.value.value
            if not node.args:
                return None
            iterable = _try_resolve(node.args[0], env)
            if isinstance(iterable, list):
                return sep.join(iterable)
            if isinstance(iterable, str):
                # Joining a single string yields the string verbatim.
                return iterable
        return None
    return None


def collect_assignments(tree: ast.AST) -> dict[str, object]:
    """Walk the module AST and collect resolvable name-bindings.

    Module-level + function-scope are merged into a single flat dict, which
    is sufficient for the codebase patterns we audit (no name shadowing in
    the affected helpers). Re-assignment uses last-wins ordering.
    """
    env: dict[str, object] = {}

    # First pass: module-level (including class bodies which we ignore here).
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for tgt in node.targets:
                if isinstance(tgt, ast.Name):
                    val = _try_resolve(node.value, env)
                    if val is not None:
                        env[tgt.id] = val
        elif isinstance(node, ast.AnnAssign):
            if isinstance(node.target, ast.Name) and node.value is not None:
                val = _try_resolve(node.value, env)
                if val is not None:
                    env[node.target.id] = val
    return env


# --- Chain walking ---------------------------------------------------------

def find_table_in_chain(select_call: ast.Call) -> tuple[str | None, bool]:
    """Walk back from a ``.select()`` Call to find the nearest ``.table()``
    / ``.from_()`` call in the same chain. Returns ``(table_name, ok)``;
    ``ok=False`` when the chain shape is unrecognized.

    The "nearest" rule (per task spec): if there are multiple ``.table()``
    calls in the chain, use the LAST one before ``.select()`` — i.e., the
    one closest to ``.select()`` walking up via ``.func.value``.
    """
    if not isinstance(select_call.func, ast.Attribute):
        return None, False
    cur = select_call.func.value
    table_name: str | None = None
    while True:
        if isinstance(cur, ast.Call) and isinstance(cur.func, ast.Attribute):
            if cur.func.attr in ("table", "from_"):
                if cur.args and isinstance(cur.args[0], ast.Constant) and isinstance(
                    cur.args[0].value, str
                ):
                    table_name = cur.args[0].value
                    return table_name, True
                # Dynamic table name — chain unrecognized.
                return None, False
            cur = cur.func.value
        elif isinstance(cur, ast.Attribute):
            cur = cur.value
        else:
            # Reached a Name / Subscript / something terminal without
            # finding ``.table()``. Chain shape unrecognized.
            return None, False


# --- Column extraction -----------------------------------------------------

def split_select_literal(literal: str) -> list[str]:
    """Split a PostgREST ``.select(...)`` literal into top-level columns.

    Strips embed sub-selects like ``foo!inner(col1, col2)`` because they
    target a different table; the parent ``.select()`` only contributes
    its top-level column names to the column-existence check.
    """
    # Remove embed sub-selects: scan and excise anything from
    # ``ident!modifier(`` (or just ``ident(``) up to its matching ``)``.
    out_chars: list[str] = []
    i = 0
    while i < len(literal):
        m = _EMBED_RE.match(literal, i)
        if m:
            # Skip the matched prefix and the balanced parens.
            depth = 1
            j = m.end()
            while j < len(literal) and depth > 0:
                if literal[j] == "(":
                    depth += 1
                elif literal[j] == ")":
                    depth -= 1
                j += 1
            i = j
        else:
            out_chars.append(literal[i])
            i += 1
    cleaned = "".join(out_chars)

    cols: list[str] = []
    for part in cleaned.split(","):
        col = part.strip()
        if not col:
            continue
        # Wildcard means "all columns" — can't statically validate.
        if col == "*":
            continue
        # Skip raw embed leftovers without parens (defensive).
        if "!" in col or ")" in col or "(" in col:
            continue
        # PostgREST aliasing: ``alias:column`` casts the column into a
        # response key. Only the right-hand side is the actual DB column.
        if ":" in col:
            col = col.split(":", 1)[1].strip()
            if not col:
                continue
        # PostgREST type casts: ``column::type`` requests an output cast.
        if "::" in col:
            col = col.split("::", 1)[0].strip()
            if not col:
                continue
        cols.append(col)
    return cols


# --- Linter ----------------------------------------------------------------

def lint_file(
    path: Path,
    schema: dict[str, set[str]],
) -> tuple[list[str], list[str]]:
    """Lint a single Python file. Returns ``(violations, warnings)``."""
    src = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(src, filename=str(path))
    except SyntaxError as exc:
        return [], [f"{path}: SyntaxError parsing file: {exc}"]

    env = collect_assignments(tree)
    if path.is_absolute():
        try:
            rel = path.relative_to(REPO_ROOT)
        except ValueError:
            # File is outside the repo (e.g., a tmp_path test fixture). Fall
            # back to the absolute path so the report still pinpoints it.
            rel = path
    else:
        rel = path

    violations: list[str] = []
    warnings: list[str] = []

    for node in ast.walk(tree):
        if not (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "select"
        ):
            continue
        if not node.args:
            continue
        arg0 = node.args[0]

        # Resolve the literal value, if possible.
        resolved = _try_resolve(arg0, env)
        if not isinstance(resolved, str):
            warnings.append(
                f"{rel}:{node.lineno}: select(...) arg is dynamic — "
                f"static check skipped"
            )
            continue

        # Skip wildcard selects.
        if resolved.strip() == "*":
            continue

        table_name, ok = find_table_in_chain(node)
        if not ok or not table_name:
            warnings.append(
                f"{rel}:{node.lineno}: could not resolve .table()/.from_() "
                f"in chain — static check skipped"
            )
            continue

        valid_cols = schema.get(table_name)
        if valid_cols is None:
            warnings.append(
                f"{rel}:{node.lineno}: table '{table_name}' not found in "
                f"{SCHEMA_NAME} schema — check skipped"
            )
            continue

        for col in split_select_literal(resolved):
            if col not in valid_cols:
                violations.append(
                    f"{rel}:{node.lineno}: column '{col}' not in "
                    f"{SCHEMA_NAME}.{table_name}"
                )

    return violations, warnings


def expand_paths(args_paths: list[str]) -> list[Path]:
    if args_paths:
        out: list[Path] = []
        for raw in args_paths:
            p = Path(raw)
            if not p.is_absolute():
                p = REPO_ROOT / p
            if p.is_dir():
                out.extend(sorted(p.rglob("*.py")))
            elif p.exists():
                out.append(p)
            else:
                # Treat as glob pattern relative to repo root.
                matched = sorted(REPO_ROOT.glob(raw))
                out.extend(m for m in matched if m.suffix == ".py")
        return out
    out = []
    for pattern in DEFAULT_SCAN_GLOBS:
        out.extend(sorted(REPO_ROOT.glob(pattern)))
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Static schema-drift check for Supabase .select() literals."
    )
    parser.add_argument(
        "paths",
        nargs="*",
        help="Files or directories to lint (default: api/*.py services/*.py)",
    )
    parser.add_argument(
        "--types-file",
        default=None,
        help="Path to database.types.ts (default: auto-detect)",
    )
    args = parser.parse_args(argv)

    types_path = (
        Path(args.types_file).resolve() if args.types_file else find_types_file()
    )
    schema = parse_database_types(types_path)

    files = expand_paths(args.paths)
    if not files:
        print("No Python files found to lint.", file=sys.stderr)
        return 0

    all_violations: list[str] = []
    all_warnings: list[str] = []
    files_with_violations: set[str] = set()

    for f in files:
        violations, warnings = lint_file(f, schema)
        for v in violations:
            print(v)
            files_with_violations.add(v.split(":", 1)[0])
        all_violations.extend(violations)
        all_warnings.extend(warnings)

    for w in all_warnings:
        print(f"WARNING: {w}", file=sys.stderr)

    if all_violations:
        print(
            f"\nFound {len(all_violations)} schema-drift violations across "
            f"{len(files_with_violations)} files."
        )
        return 1

    print(f"OK: scanned {len(files)} files, no schema-drift violations found.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
